### PR TITLE
Add 'proxy' command to generate config file for reverse proxy

### PR DESCRIPTION
**Pull request by mbryzek**
- from sbt: run proxy flow/catalog flow/common flow/delivery_window flow/experience flow/fulfillment flow/harmonization flow/location flow/organization flow/payment flow/reference flow/search flow/tracking flow/user

 - output will be written to /tmp/proxy.config - sample:
```yaml
catalog:
  - host: https://catalog.api.flow.io
  - operations:
    - DELETE /:organization/attributes/:name
    - GET /:organization/attributes/:name
common:
  - host: https://api.flow.io
  - operations:
    - GET /_internal_/healthcheck
```

### CODE REVIEW

**Comment by chrhicks** [comment]
(accidentally updated the formatting of your comment!)

Think the format is okay..

Curious your thoughts on:
- Why not build it from the oneapi (aka only build config for the public stuff)
- Is there explicit noting of whats public (or private)?

**Comment by mbryzek** [comment]
- Why not build it from the oneapi (aka only build config for the public stuff)

The core problem is to build from the "api" project, we lose the actual service (e.g. user) that the route belongs to. So I think the paths are 1. inject attributes into api to do the reverse lookup; 2: just build from the core service definitions. I think #2 is simpler - and given we can build at same time as we create the full 'api' in practice I don't see risk of divergence.

> Is there explicit noting of whats public (or private)?

Have not gotten to this yet. We're missing a piece of metadata that says "also generate a routing file for say payment-internal" - i.e. we don't actually know the APIs we want to route for.

I'm thinking a possible path is to use full host headers - e.g. "https://payment.api.flow.io" when requesting a private path. Process would be:

  - check if it is public (by virtue of being in configuration file)
  - if not, auth the token and confirm admin membership exists for organization "flow" (configuration constant)
  - if succeeds, forward request to the service identified by the host header.

**Comment by chrhicks** [comment]
> . I think #2 is simpler - and given we can build at same time as we create the full 'api' in practice I don't see risk of divergence.

Yea. Polluting the `api` with metadata thats not related to generating code is not great.

> I'm thinking a possible path is to use full host headers - e.g. "https://payment.api.flow.io" when requesting a private path.

So the burden would be on us (flow employees) to remember to tack on the `HOST` header. Is that annoying?

Like the idea of the config only containing public routes and then falling back to something else to figure out private routing.

**Comment by mbryzek** [comment]
> So the burden would be on us (flow employees) to remember to tack on the HOST header. Is that annoying?

In reality, we will have to do something different because either:

  a. use the client for the 'api' repo - in which case the private routes simply aren't available in the client
  b. use the application specific client - in which case base_url is already set for us

My gut feeling is it will thus be transparent to us - we can continue development like we are today, using the core API clients, and get the benefits of:

  - all requests routed through api.flow.io
  - authorization for any private apis

**Pull request merged**
